### ISSUE TITLE
Missing the images of the VRD dataset

### ISSUE THREAD

**Issue by ZENGXH** [doubledaibo/drnet#1]
Hi @doubledaibo ,

Thanks for releasing your great work. I am writing to ask if you know where is the link for the images in the VRD dataset? I am sorry to ask such a simple question since I can only find the annotation in mat/python format in http://cs.stanford.edu/people/ranjaykrishna/vrd/.

Thanks in advance for your help!

**Comment by doubledaibo** [comment]
Hi @ZENGXH ,
 Please download the dataset [http://cs.stanford.edu/people/ranjaykrishna/vrd/dataset.zip] and read its readme.txt, which contains all the information you need.
  Regards,

**Comment by ZENGXH** [comment]
Thanks!

**Comment by yanxp** [comment]
@ZENGXH  Can you be able to train the model?

**Comment by ZENGXH** [comment]
@yanxp Sorry I did not train the model.

**Comment by yanxp** [comment]
@ZENGXH  Thanks.Have you tested sucessfully? How to set some parameter? Do you have some relative files? I meet some problems.
