### ISSUE TITLE
Hello, Where is gt_file?

### ISSUE THREAD

**Issue by yanxp** [doubledaibo/drnet#3]
How to generate gt_file? What is the format?

**Comment by doubledaibo** [comment]
Please read the test script. In the argument part, formats of several important inputs are showed. You can write some script to turn the dataset into needed inputs.

**Comment by yanxp** [comment]
@doubledaibo Hello,I meet the problem. How to solve it? Thanks!  
net_out = net.forward(**forward_args)
  File "/home/yarley/yanxp/drnet/tools/../caffe/python/caffe/pycaffe.py", line 123, in _Net_forward
    raise Exception('Input blob arguments do not match net inputs.')
Exception: Input blob arguments do not match net inputs.

**Comment by doubledaibo** [comment]
Exception: Input blob arguments do not match net inputs.

You can check the prototxt you use, and the actual data blobs (names and sizes) you feed into the net.
